apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-deployment
  labels:
    app: youtube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
        - name: youtube-container
          image: sriramyaganni/youtube-webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          # IMPORTANT: Environment Variables
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "development"
            - name: MONGO_URI
              value: "mongodb://localhost:27017/test"   # 👉 replace with your real DB

---
apiVersion: v1
kind: Service
metadata:
  name: youtube-service
spec:
  selector:
    app: youtube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
